# This is a basic workflow that is manually triggered

name: Deploy-Websites

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      env:
        GIT_UPDATE_PATH_1: ${{ secrets.GIT_UPDATE_PATH_1 }}
        GIT_UPDATE_PATH_2: ${{ secrets.GIT_UPDATE_PATH_2 }}
      run: |
        curl --location --request POST "$GIT_UPDATE_PATH_1"
        curl --location --request POST "$GIT_UPDATE_PATH_2"
